### PR TITLE
External keycloak

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@ziccardi @mfischelmayer I am adding support for the decoupled Keycloak

**Comment by ziccardi** [comment]
LGTM

**Comment by matzew** [comment]
@mfischelmayer is there interest in landing this upstream, in your repo, as well ?

**Comment by mfischelmayer** [comment]
Hi @matzew @ziccardi 
Our company has decided to build completely on another solution … :-(
This is the reason why I did not go on with this …
But very cool that there is some use for it :-)
I will update my readme that everyone should use this fork.

**Pull request merged**
